language: bash

sudo: required

services:
- docker

install:
- wget https://github.com/scaleway/scaleway-cli/releases/download/v1.5.0/scw_1.5.0_amd64.deb && sudo dpkg -i scw*.deb && rm -f scw*.deb && scw version
- wget https://github.com/moul/anonuuid/releases/download/v1.0.0/anonuuid_1.0_amd64.deb && sudo dpkg -i anonuuid*.deb && rm -f anonuuid*.deb && anonuuid --version

before_script:
- if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then make prepare; fi
script:
- if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then make build;   fi
- if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then make test;    fi
- if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then make deploy;  fi
- if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then make clean;   fi
after_failure:
- if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then make clean;   fi
